// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/leakingtapan/sonoff/apis/models"
)

// DescribeDevicesReader is a Reader for the DescribeDevices structure.
type DescribeDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDescribeDevicesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDescribeDevicesOK creates a DescribeDevicesOK with default headers values
func NewDescribeDevicesOK() *DescribeDevicesOK {
	return &DescribeDevicesOK{}
}

/*DescribeDevicesOK handles this case with default header values.

The device list
*/
type DescribeDevicesOK struct {
	Payload models.Devices
}

func (o *DescribeDevicesOK) Error() string {
	return fmt.Sprintf("[GET /devices][%d] describeDevicesOK  %+v", 200, o.Payload)
}

func (o *DescribeDevicesOK) GetPayload() models.Devices {
	return o.Payload
}

func (o *DescribeDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeDevicesDefault creates a DescribeDevicesDefault with default headers values
func NewDescribeDevicesDefault(code int) *DescribeDevicesDefault {
	return &DescribeDevicesDefault{
		_statusCode: code,
	}
}

/*DescribeDevicesDefault handles this case with default header values.

Internal Server Error
*/
type DescribeDevicesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the describe devices default response
func (o *DescribeDevicesDefault) Code() int {
	return o._statusCode
}

func (o *DescribeDevicesDefault) Error() string {
	return fmt.Sprintf("[GET /devices][%d] describeDevices default  %+v", o._statusCode, o.Payload)
}

func (o *DescribeDevicesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeDevicesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
