// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeDevicesParams creates a new DescribeDevicesParams object
// with the default values initialized.
func NewDescribeDevicesParams() *DescribeDevicesParams {

	return &DescribeDevicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeDevicesParamsWithTimeout creates a new DescribeDevicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeDevicesParamsWithTimeout(timeout time.Duration) *DescribeDevicesParams {

	return &DescribeDevicesParams{

		timeout: timeout,
	}
}

// NewDescribeDevicesParamsWithContext creates a new DescribeDevicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeDevicesParamsWithContext(ctx context.Context) *DescribeDevicesParams {

	return &DescribeDevicesParams{

		Context: ctx,
	}
}

// NewDescribeDevicesParamsWithHTTPClient creates a new DescribeDevicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeDevicesParamsWithHTTPClient(client *http.Client) *DescribeDevicesParams {

	return &DescribeDevicesParams{
		HTTPClient: client,
	}
}

/*DescribeDevicesParams contains all the parameters to send to the API endpoint
for the describe devices operation typically these are written to a http.Request
*/
type DescribeDevicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe devices params
func (o *DescribeDevicesParams) WithTimeout(timeout time.Duration) *DescribeDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe devices params
func (o *DescribeDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe devices params
func (o *DescribeDevicesParams) WithContext(ctx context.Context) *DescribeDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe devices params
func (o *DescribeDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe devices params
func (o *DescribeDevicesParams) WithHTTPClient(client *http.Client) *DescribeDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe devices params
func (o *DescribeDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
