// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDeviceByIDParams creates a new GetDeviceByIDParams object
// with the default values initialized.
func NewGetDeviceByIDParams() *GetDeviceByIDParams {
	var ()
	return &GetDeviceByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeviceByIDParamsWithTimeout creates a new GetDeviceByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeviceByIDParamsWithTimeout(timeout time.Duration) *GetDeviceByIDParams {
	var ()
	return &GetDeviceByIDParams{

		timeout: timeout,
	}
}

// NewGetDeviceByIDParamsWithContext creates a new GetDeviceByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeviceByIDParamsWithContext(ctx context.Context) *GetDeviceByIDParams {
	var ()
	return &GetDeviceByIDParams{

		Context: ctx,
	}
}

// NewGetDeviceByIDParamsWithHTTPClient creates a new GetDeviceByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeviceByIDParamsWithHTTPClient(client *http.Client) *GetDeviceByIDParams {
	var ()
	return &GetDeviceByIDParams{
		HTTPClient: client,
	}
}

/*GetDeviceByIDParams contains all the parameters to send to the API endpoint
for the get device by Id operation typically these are written to a http.Request
*/
type GetDeviceByIDParams struct {

	/*DeviceID
	  ID of the device

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get device by Id params
func (o *GetDeviceByIDParams) WithTimeout(timeout time.Duration) *GetDeviceByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get device by Id params
func (o *GetDeviceByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get device by Id params
func (o *GetDeviceByIDParams) WithContext(ctx context.Context) *GetDeviceByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get device by Id params
func (o *GetDeviceByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get device by Id params
func (o *GetDeviceByIDParams) WithHTTPClient(client *http.Client) *GetDeviceByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get device by Id params
func (o *GetDeviceByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the get device by Id params
func (o *GetDeviceByIDParams) WithDeviceID(deviceID string) *GetDeviceByIDParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the get device by Id params
func (o *GetDeviceByIDParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeviceByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
