// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetDeviceStateByIDParams creates a new SetDeviceStateByIDParams object
// with the default values initialized.
func NewSetDeviceStateByIDParams() *SetDeviceStateByIDParams {
	var ()
	return &SetDeviceStateByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetDeviceStateByIDParamsWithTimeout creates a new SetDeviceStateByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetDeviceStateByIDParamsWithTimeout(timeout time.Duration) *SetDeviceStateByIDParams {
	var ()
	return &SetDeviceStateByIDParams{

		timeout: timeout,
	}
}

// NewSetDeviceStateByIDParamsWithContext creates a new SetDeviceStateByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetDeviceStateByIDParamsWithContext(ctx context.Context) *SetDeviceStateByIDParams {
	var ()
	return &SetDeviceStateByIDParams{

		Context: ctx,
	}
}

// NewSetDeviceStateByIDParamsWithHTTPClient creates a new SetDeviceStateByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetDeviceStateByIDParamsWithHTTPClient(client *http.Client) *SetDeviceStateByIDParams {
	var ()
	return &SetDeviceStateByIDParams{
		HTTPClient: client,
	}
}

/*SetDeviceStateByIDParams contains all the parameters to send to the API endpoint
for the set device state by Id operation typically these are written to a http.Request
*/
type SetDeviceStateByIDParams struct {

	/*DeviceID
	  ID of the device

	*/
	DeviceID string
	/*State
	  The state of the device (on or off)

	*/
	State string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set device state by Id params
func (o *SetDeviceStateByIDParams) WithTimeout(timeout time.Duration) *SetDeviceStateByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set device state by Id params
func (o *SetDeviceStateByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set device state by Id params
func (o *SetDeviceStateByIDParams) WithContext(ctx context.Context) *SetDeviceStateByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set device state by Id params
func (o *SetDeviceStateByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set device state by Id params
func (o *SetDeviceStateByIDParams) WithHTTPClient(client *http.Client) *SetDeviceStateByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set device state by Id params
func (o *SetDeviceStateByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the set device state by Id params
func (o *SetDeviceStateByIDParams) WithDeviceID(deviceID string) *SetDeviceStateByIDParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the set device state by Id params
func (o *SetDeviceStateByIDParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithState adds the state to the set device state by Id params
func (o *SetDeviceStateByIDParams) WithState(state string) *SetDeviceStateByIDParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the set device state by Id params
func (o *SetDeviceStateByIDParams) SetState(state string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *SetDeviceStateByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	// path param state
	if err := r.SetPathParam("state", o.State); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
