name: Container Images

on:
  push:
    branches:
      - master
    tags:
      - v.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Push to Dockerhub registry
      run: |
        BRANCH=$(echo $GITHUB_REF | cut -d'/' -f3)
        REPO=chengpan/sonoff
        if [ "$BRANCH" = "master" ]; then
          TAG="latest"
        else
          TAG=$BRANCH
        fi
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker buildx build \
          -t $REPO:$TAG \
          --platform=linux/arm/v7,linux/amd64 \
          --output="type=image,push=true" .
